name: github pages

on:
  push:
    branches: [ master ]

  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "repository=$REPOSITORY" >> $GITHUB_OUTPUT
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          cache: true
      
      - name: Ensure correct Flutter path
        run: echo "$HOME/flutter/bin" >> $GITHUB_PATH
        
      - name: Show versions (sanity check)
        run: |
          flutter --version
          dart --version
          which flutter
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --release --base-href /${{ steps.version.outputs.repository }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          